name: Build, test and publish

on: push

permissions:
  id-token: write
  contents: read

jobs:
  build12:
    uses: ./.github/workflows/build.yaml
    with:
      oarepo: "12"
      python-version: "3.12"

  build_python314:
    uses: ./.github/workflows/build.yaml
    with:
      oarepo: "12"
      python-version: "3.14"

  publish:
    runs-on: ubuntu-latest
    needs:
      - build12
      - build_python314
    steps:
      - name: Use built artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: List files
        run: |
          ls -la
          ls -la dist

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
